language: ruby
rvm:
  - 2.2
  - jruby
  - 2.0.0-p247

install: bundle install --jobs=3 --retry=3

script:
  - 'HANAMI_ENV=test bundle exec hanami db create'
  - 'HANAMI_ENV=test bundle exec hanami db migrate'
  - 'bundle exec rake test'

  